# ==========================
# Etapa 1 - Build
# ==========================
FROM maven:3.9.11-eclipse-temurin-21 AS builder

WORKDIR /build

COPY . .

RUN mvn clean package -DskipTests

# ==========================
# Etapa 2 - Runtime
# ==========================
FROM eclipse-temurin:21-jre

WORKDIR /app

# Crear usuario y grupo para la aplicación
RUN groupadd --system app && useradd --system --gid app app

# Copiar la aplicación
COPY --from=builder /build/target/springboot-lab-0.0.1-SNAPSHOT.jar app.jar

# Cambiar propietario de la aplicación
RUN chown app:app app.jar

# Ejecutar como usuario de la aplicación
USER app

EXPOSE 8080

ENTRYPOINT ["java","-jar","app.jar"]