services:

    postgres:
        image: postgres:17
        container_name: postgres

        # Si este contenedor se cae, intenta levantarlo nuevamente.
        # Pero si yo lo detuve manualmente, respeta mi decisión.
        restart: unless-stopped

        environment:
            POSTGRES_DB: springboot_lab
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres

        # exponse el puerto unicamente al los servicios internos de docker y
        # evita qu pueda ser accedido desde el host
        expose:
            - "5432"

        volumes:
            - postgres-data:/var/lib/postgresql/data

        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d springboot_lab"]
            interval: 5s
            timeout: 5s
            retries: 5
            start_period: 10s

        # Red personalizada
        networks:
            - backend
    app:
        build: .
        container_name: springboot-lab

        restart: unless-stopped

        # Limita el uso de memoria el host a 512MB
        mem_limit: 512m

        # Limita el uso de cpu a medio nucleo
        cpus: 0.5

        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "3"

        depends_on:
            postgres:
                 condition: service_healthy

        environment:
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_NAME: ${DB_NAME}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}

        ports:
            - "8080:8080"

        networks:
            - backend

volumes:
    postgres-data:

networks:

    backend:
        driver: bridge

